### ISSUE TITLE
add a readme

### ISSUE THREAD

**Issue by maerten** [guatedude2/ember-flowtype#1]
Hi, i wanted to try out this lib, how do i get this installed?:)

**Comment by guatedude2** [comment]
Let me update the README.md

**Comment by maerten** [comment]
Actually, is this about flowtype.org?

**Comment by guatedude2** [comment]
Ah no, sorry this is for FlowType.JS (http://simplefocus.com/flowtype/)

**Comment by guatedude2** [comment]
Added installation instructions and link to LICENSE.md
